site_name: DevopsPilot
site_url: https://devopspilot1.github.io/
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    primary: custom
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.expand
    - navigation.indexes
    - toc.follow
    - toc.integrate
copyright:  Copyright &copy; 2021 - 2025 DevopsPilot
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-EKDQC3L9T7

nav:
  - Linux Commands:
    - Part 1: linux-commands/part-1.md
    - Part 2: linux-commands/part-2.md
    - Part 3: linux-commands/part-3.md
    - Part 4: linux-commands/part-4.md
    - Part 5: linux-commands/part-5.md
    - Part 6: linux-commands/part-6.md
    - Part 7: linux-commands/part-7.md
    - Part 8: linux-commands/part-8.md
    - Part 9: linux-commands/part-9.md
  - SSH:
    - Ssh: ssh/ssh.md
  - Shellscript:
    - Part 1: shellscript/part-1.md
    - Part 2: shellscript/part-2.md
    - Part 3: shellscript/part-3.md
    - Part 4: shellscript/part-4.md
  - Git:
    - How to create github account: git/how-to-create-github-account.md
    - How to install git in linux: git/how-to-install-git-in-linux.md
    - How to create public repository in github: git/how-to-create-public-repository-in-github.md
    - How to clone the github public repository: git/how-to-clone-the-public-repository.md
    - How to create private repository: git/how-to-create-private-repository.md
    - How to push the changes to github repository: git/how-to-push-the-changes-to-github-repository.md
    - Tutorials:
      - Git Basics: git/tutorials/02-basics.md
      - Git Branching and Merging: git/tutorials/03-branching-merging.md
      - Git Pull and Fetch: git/tutorials/04-pull_fetch.md
      - Git Reset: git/tutorials/05-reset.md
      - Git Tags: git/tutorials/06-tags.md
      - Git Stash: git/tutorials/07-stash.md
      - Common Issues in Git: git/tutorials/08-issues-faced.md
      - How to Fix Merge Conflicts: git/tutorials/09-how-to-fix-merge-conflict.md
      - How to Create Pull Request in GitHub: git/tutorials/10-how-to-create-pull-request-in-github.md
      - How to Fix Merge Conflicts in Pull Request: git/tutorials/11-how-to-fix-merge-conflict-in-pull-request.md
      - Git Rebase: git/tutorials/12-rebase.md
      - Git Visual Diff and Merge Tools: git/tutorials/visual_diff_merge.md
  - Build Tools:
    - Maven:
      - How to install Java and compile a single Java file: build-tools/maven/install-java-compile.md
      - How to install Maven in Linux: build-tools/maven/install-maven.md
      - What is Maven?: build-tools/maven/what-is-maven.md
      - Generate a sample java application using maven: build-tools/maven/generate-a-sample-java-application-using-maven.md
      - How to create a GitHub repository and push a Hello World Java 21 Maven Project: build-tools/maven/how-to-create-a-github-repository-and-push-a-sample-java-maven-project.md
  - Web Server:
    - Nginx:
      - How to install nginx in Linux: webserver/nginx/how-to-install-nginx.md
    - Tomcat:
      - How to install Tomcat: webserver/tomcat/installation.md
      - How to manually deploy the java application to Tomcat 9 webserver: webserver/tomcat/how-to-manually-deploy-java-application-to-tomcat.md
      - How to deploy the java application to Tomcat 9 webserver using Maven: webserver/tomcat/how-to-deploy-java-application-to-tomcat-using-maven.md
  - Jenkins:
    - Tutorials:
      - How to install Jenkins with Java 21 on Ubuntu 24.04: jenkins/tutorials/how-to-install-jenkins-with-java-21-on-ubuntu.md
      - How to complete the initial setup after installing Jenkins: jenkins/tutorials/how-to-complete-the-initial-setup-after-installing-jenkins.md
      - How to create a Freestyle project in Jenkins to build a Maven Java project: jenkins/tutorials/how-to-create-a-freestyle-project-to-build-a-maven-java-project.md
      - How to install the Maven plugin in Jenkins: jenkins/tutorials/how-to-create-a-maven-project-in-jenkins-to-build-a-maven-java-project.md
      - How to install Maven using Jenkins Tools: jenkins/tutorials/how-to-install-the-maven-plugin-in-jenkins.md
      - How to create a Maven project in Jenkins to build a Maven Java project: jenkins/tutorials/how-to-install-maven-from-jenkins-tools.md
      - How to store a Github Token safely in Jenkins Credentials: jenkins/tutorials/how-to-store-a-github-token-safely-in-jenkins-credentials.md
      - How to create a Maven project in Jenkins with Private Github Repository: jenkins/tutorials/how-to-create-a-maven-project-in-jenkins-with-private-github-repository.md
      - How to create a Pipeline in Jenkins using Pipeline Script: jenkins/tutorials/how-to-create-a-pipeline-in-jenkins.md
      - How to write a Jenkinsfile: jenkins/tutorials/how-to-write-jenkinsfile.md
      - How to create a Pipeline in Jenkins using Jenkinsfile: jenkins/tutorials/how-to-create-a-pipeline-in-jenkins-using-jenkinsfile.md
      - Jenkinsfile to build a Java Maven Project: jenkins/tutorials/jenkinsfile-to-build-a-java-maven-project.md
      - How to use the tools block in Jenkinsfile to refer to Maven: jenkins/tutorials/how-to-use-tools-block-in-jenkinsfile.md
      - How to enable GitHub Webhook to trigger the Jenkins pipeline: jenkins/tutorials/how-to-enable-github-webhook-to-trigger-the-jenkins-pipeline.md
      - Jenkinsfile to trigger the Jenkins Pipeline using Poll SCM: jenkins/tutorials/jenkinsfile-to-trigger-the-jenkins-pipeline-using-poll-scm.md
      - Jenkinsfile to trigger the Jenkins Pipeline using Cron: jenkins/tutorials/jenkinsfile-to-trigger-the-jenkins-pipeline-using-cron.md
      - Jenkinsfile to trigger the Pipeline from the Upstream Pipeline: jenkins/tutorials/jenkinsfile-to-trigger-the-pipeline-from-the-upstream-pipeline.md
      - Jenkinsfile to trigger other Jenkins Pipeline from the stage: jenkins/tutorials/jenkinsfile-to-trigger-other-jenkins-pipeline-from-the-stage.md
      - Generate the code for Jenkinsfile using Declarative Directive Generator: jenkins/tutorials/generate-the-code-for-jenkinsfile-using-declarative-directive-generator.md
      - How to Replay the Jenkins Pipeline: jenkins/tutorials/how-to-replay-the-jenkins-pipeline.md
      - How to use Options in Jenkinsfile: jenkins/tutorials/use-of-options-in-jenkinsfile.md
    - Configuration:
      - How to install plugins in Jenkins: jenkins/configuration/how-to-install-plugins.md
      - Global Tool Configurations: jenkins/configuration/global-tool-configurations.md
      - How to store credentials in Jenkins: jenkins/configuration/how-to-store-credentials-in-jenkins.md
      - How to restore deleted job in Jenkins: jenkins/configuration/how-to-restore-deleted-job.md
    - Pipelines:
      - How to create pipeline job in Jenkins: jenkins/pipelines/how-to-create-pipeline-job.md
      - How to write a Jenkinsfile to build a Maven project: jenkins/pipelines/jenkinsfile-to-build-maven-project.md
      - How to write a Jenkinsfile to build a Maven project and deploy to Apache Tomcat webserver: jenkins/pipelines/jenkinsfile-to-build-maven-project-and-deploy-to-tomcat.md
      - How to write a Jenkinsfile to build a Maven project, build and push docker image to Dockerhub and deploy the container to same server: jenkins/pipelines/jenkinsfile-to-build-docker-image-push-deploy-to-same-server.md
      - How to write a Jenkinsfile to build a Maven project, build and push docker image to Jfrog artifactory and deploy the container to same server: jenkins/pipelines/jenkinsfile-to-build-docker-image-push-to-artifactory.md
    - Other Topics:
      - How to create a Job automatically using Seed Jenkins plugin and Job DSL script: jenkins/other-topics/how-to-create-a-job-automatically-using-jobdsl.md
  - Docker:
    - Tutorials:
      - What is Docker: docker/tutorials/what-is-docker.md
      - How to install docker: docker/tutorials/how-to-install-docker.md
      - Docker Images vs Docker Containers: docker/tutorials/docker-images-vs-containers.md
      - Create docker image for nginx and html file: docker/tutorials/create-docker-image-nginx-html.md
      - Pull nginx docker image from dockerhub, tag and push to your public repo in dockerhub account: docker/tutorials/pull-push-docker-image-to-public-repository.md
      - Pull nginx docker image from dockerhub, tag and push to your private repository in dockerhub account: docker/tutorials/pull-push-docker-image-to-private-repository.md
    - Dockerfile:
      - How to write Dockerfile for installing packages: docker/dockerfiles/create-dockerfile-to-install-packages.md
      - How to write a dockerfile for installing openjdk15: docker/dockerfiles/create-a-dockerfile-for-installing-openjdk15.md
      - How to create a multi stage Dockerfile: docker/dockerfiles/create-multi-stage-dockerfile.md
      - How to write a dockerfile for running a java application (*.war) in Apache tomcat webserver: docker/dockerfiles/how-to-write-a-dockerfile-for-running-war-file-in-tomcat.md
  - Sonarqube:
    - How to integrate Sonarqube Quality Gate in Jenkins Pipeline: sonarqube/quality-gate.md
  - K8s:
    - Introduction:
      - What is Kubernetes?: kubernetes/tutorials/what-is-kubernetes.md
    - Setup and Installation:
      - Installing Minikube: kubernetes/tutorials/how-to-install-minikube-in-linux.md
      - Installing kubectl: kubernetes/tutorials/how-to-install-kubectl-in-linux.md
    - Core Concepts:
      - Namespaces: kubernetes/tutorials/how-to-create-namespace-in-kubernetes.md
      - Pods: kubernetes/tutorials/how-to-create-pod-in-kubernetes.md
    - Workload Resources:
      - ReplicaSets: kubernetes/tutorials/how-to-create-replicaset-in-kubernetes.md
      - Deployments: kubernetes/tutorials/how-to-create-deployment-in-kubernetes.md
      - StatefulSets: kubernetes/tutorials/how-to-create-statefulset-in-kubernetes.md
      - DaemonSets: kubernetes/tutorials/how-to-create-daemonset-in-kubernetes.md
      - Jobs and CronJobs: kubernetes/tutorials/how-to-create-job-cronjob-in-kubernetes.md
    - Service & Networking:
      - Services: kubernetes/tutorials/how-to-create-service-in-kubernetes.md
      - Ingress: kubernetes/tutorials/how-to-create-ingress-in-kubernetes.md
      - Ingress Controllers:
        - Nginx Ingress Controller: kubernetes/tutorials/how-to-install-ingress-controller.md
    - Configuration & Storage:
      - ConfigMaps: kubernetes/tutorials/how-to-create-configmap-in-kubernetes.md
      - Secrets: kubernetes/tutorials/how-to-create-secret-in-kubernetes.md
      - Storage Classes: kubernetes/tutorials/how-to-create-storage-class-in-kubernetes.md
      - PV and PVC: kubernetes/tutorials/how-to-create-pv-pvc-in-kubernetes.md
    - Application Management:
      - Scaling: kubernetes/tutorials/how-to-scale-deployment-in-kubernetes.md
      - Rolling Updates: kubernetes/tutorials/how-to-create-rolling-update-in-kubernetes.md
      - Rollbacks: kubernetes/tutorials/how-to-rollback-deployment-in-kubernetes.md
    - Security:
      - Cert Manager: kubernetes/tutorials/how-to-install-cert-manager.md
  - Helm:
    - Helm chart basics: helm/basics.md
    - Helm commands: helm/commands.md
  - Terraform:
    - AWS:
      - Terraform script to create AWS Codebuild project: terraform/aws/codebuild-helloworld.md
      - Terraform script to create AWS Codedeploy: terraform/aws/codedeploy-helloworld.md
      - Terraform script to create AWS Codepipeline: terraform/aws/codepipeline-helloworld.md
  - SSL:
    - How to configure free Let’s Encrypt SSL/TLS Certificates with NGINX and auto renew certificates: ssl/how-to-configure-free-letsencrypt-ssl-tls-certificates-with-nginx.md
    - How to configure free single Let’s Encrypt SSL/TLS Certificate with NGINX for multiple subdomains and auto renew certificate: ssl/how-to-configure-free-letsencrypt-ssl-tls-certificates-with-nginx-for-subdomains.md
    - How to configure free single Let’s Encrypt SSL/TLS wildcard Certificate with Nginx: ssl/how-to-configure-free-letsencrypt-ssl-tls-wildcard-certificates-with-nginx-for-subdomains.md
    - How to generate self signed certificate using openssl: ssl/self-signed-certificate-using-openssl.md
  - Interview Questions:
    - Linux commands Interview Questions: interview-questions/linux-commands.md
    - Git Interview Questions: interview-questions/git.md
    # - Maven Interview Questions: interview-questions/
    # - Jenkins Interview Questions: interview-questions/
    - Docker Interview Questions: interview-questions/docker.md
    # - Kubernetes Interview Question: interview-questions/
    - Helm Interview Questions: interview-questions/helm.md
    - Ansible Interview Questions: interview-questions/ansible.md
    # - AWS Interview Questions: interview-questions/
    # - Terraform Interview Questions: interview-questions/

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.snippets
  - tables
  - toc:
      permalink: true

plugins:
  - search