site_name: DevopsPilot
site_url: https://devopspilot1.github.io/
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: default
    primary: green

nav:
  - Linux Commands:
    - Part 1: linux-commands/part-1.md
    - Part 2: linux-commands/part-2.md
    - Part 3: linux-commands/part-3.md
    - Part 4: linux-commands/part-4.md
    - Part 5: linux-commands/part-5.md
    - Part 6: linux-commands/part-6.md
    - Part 7: linux-commands/part-7.md
    - Part 8: linux-commands/part-8.md
    - Part 9: linux-commands/part-9.md

# markdown_extensions:
#   - admonition
#   - codehilite:
#       guess_lang: false
#   - footnotes
#   # - pymdownx.arithmatex:
#   #     generic: true
#   - pymdownx.critic
#   - pymdownx.details
#   - pymdownx.emoji:
#       emoji_generator: !!python/name:pymdownx.emoji.to_svg
#   - pymdownx.inlinehilite
#   - pymdownx.mark
#   - pymdownx.smartsymbols
#   - pymdownx.tabbed:
#       alternate_style: true
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tilde

plugins:
  - search